import { ArrowRight, Mail, MapPin, MessageCircle, Phone } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import { contact, destinations, packages, socials } from '../../data/content'

export function Footer(){
  const [state,setState]=useState<'idle'|'loading'|'success'|'error'>('idle')
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setState('loading');setTimeout(()=>setState('error'),600)}
  return <footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><img src="/images/kakani-logo-transparent.png" alt="Kakani Holidays"/><p>Thoughtfully planned devotional journeys across sacred India, shaped around comfort, clarity and purpose.</p><div className="socials">{Object.entries(socials).map(([name,url])=><a href={url} target="_blank" rel="noreferrer" key={name}>{name.slice(0,2)}</a>)}</div></div><div><h3>Explore</h3>{[['Home','/'],['Destinations','/destinations'],['Tour Packages','/packages'],['Pilgrimage Guide','/pilgrimage-guide'],['Journal','/blog'],['About','/about'],['Contact','/contact']].map(([x,to])=><Link to={to} key={x}>{x}</Link>)}</div><div><h3>Sacred places</h3>{destinations.slice(0,6).map(d=><Link to={`/destinations/${d.slug}`} key={d.slug}>{d.name}</Link>)}</div><div><h3>Journeys</h3>{packages.slice(0,5).map(p=><Link to={`/packages/${p.slug}`} key={p.slug}>{p.name}</Link>)}</div><div className="footer-contact"><h3>Stay connected</h3><a href={contact.tel}><Phone/>{contact.phone}</a><a href={`mailto:${contact.email}`}><Mail/>{contact.email}</a><span><MapPin/>Hyderabad, Telangana</span><form onSubmit={submit} noValidate><label htmlFor="newsletter">Journey notes by email</label><div><input id="newsletter" type="email" required placeholder="Email address"/><button disabled={state==='loading'} aria-label="Subscribe"><ArrowRight/></button></div><small aria-live="polite">{state==='error'?'Newsletter integration is not connected yet.':state==='success'?'Thank you for subscribing.':''}</small></form></div></div><div className="container footer-bottom"><span>© 2026 Kakani Holidays Pvt. Ltd.</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><a href={contact.whatsapp}><MessageCircle/>WhatsApp</a></div></div></footer>
}
