import { AnimatePresence, motion } from 'framer-motion'
import { ChevronDown, Menu, MessageCircle, Phone, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Link, NavLink, useLocation } from 'react-router-dom'
import { articles, contact, destinations, packages } from '../../data/content'

const links=[['Home','/'],['Destinations','/destinations'],['Tour Packages','/packages'],['Pilgrimage Guide','/pilgrimage-guide'],['Blog','/blog'],['About Us','/about'],['Contact Us','/contact']]
const catalogues:Record<string,{label:string;items:{name:string;to:string;meta:string}[]}>={
  '/destinations':{label:'Sacred places',items:destinations.slice(0,6).map(d=>({name:d.name,to:`/destinations/${d.slug}`,meta:d.region}))},
  '/packages':{label:'Curated journeys',items:packages.slice(0,6).map(p=>({name:p.name,to:`/packages/${p.slug}`,meta:p.duration}))},
  '/pilgrimage-guide':{label:'Plan with clarity',items:['Temple Etiquette','Packing Guides','Darshan Information','Best Time to Visit','Festival Calendar'].map(x=>({name:x,to:'/pilgrimage-guide',meta:'Practical guide'}))},
  '/blog':{label:'From the journal',items:articles.slice(0,5).map(a=>({name:a.title,to:'/blog',meta:a.readTime}))},
}
export function Navigation(){
  const [open,setOpen]=useState(false),[mega,setMega]=useState<string|null>(null),[mobileSection,setMobileSection]=useState<string|null>(null),[compact,setCompact]=useState(false),[hidden,setHidden]=useState(false)
  const last=useRef(0), location=useLocation()
  useEffect(()=>{setOpen(false);setMega(null)},[location])
  useEffect(()=>{const onScroll=()=>{const y=scrollY;setCompact(y>40);setHidden(y>last.current&&y>180);last.current=y};addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll)},[])
  useEffect(()=>{document.body.style.overflow=open?'hidden':'';return()=>{document.body.style.overflow=''}},[open])
  useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMega(null);setOpen(false)}};addEventListener('keydown',esc);return()=>removeEventListener('keydown',esc)},[])
  return <><a className="skip-link" href="#main">Skip to content</a><header className={`site-nav ${compact?'compact':''} ${hidden?'nav-hidden':''}`}><Link className="brand" to="/"><img src="/images/kakani-logo-transparent.png" alt="Kakani Holidays Pvt. Ltd."/></Link><nav aria-label="Primary navigation">{links.map(([label,to])=><div className="nav-entry" onMouseEnter={()=>catalogues[to]&&setMega(to)} onMouseLeave={()=>setMega(null)} key={to}><NavLink to={to} end={to==='/'} onFocus={()=>catalogues[to]&&setMega(to)} aria-expanded={catalogues[to]?mega===to:undefined}>{label}{catalogues[to]&&<ChevronDown/>}</NavLink><AnimatePresence>{mega===to&&catalogues[to]&&<motion.div className="mega" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:8}} transition={{duration:.25}}><div><p>{catalogues[to].label}</p><h3>{label}</h3><span>Thoughtfully selected information for your next sacred journey.</span><Link to={to}>View all {label.toLowerCase()}</Link></div><div>{catalogues[to].items.map(item=><Link to={item.to} key={item.name}><span>{item.name}</span><small>{item.meta}</small></Link>)}</div><img src={to==='/destinations'?destinations[0].image:to==='/packages'?packages[0].image:'/images/golden-temple-hero.png'} alt=""/></motion.div>}</AnimatePresence></div>)}</nav><a className="nav-phone" href={contact.tel}><Phone/>{contact.phone}</a><button className="menu-button" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu/></button></header><AnimatePresence>{open&&<motion.div className="mobile-drawer" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true" aria-label="Navigation"><motion.div initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{ease:[.22,1,.36,1],duration:.45}}><header><Link className="brand" to="/"><img src="/images/kakani-logo-transparent.png" alt="Kakani Holidays"/></Link><button onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button></header><nav>{links.map(([label,to],i)=><motion.div initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} transition={{delay:i*.04}} key={to}>{catalogues[to]?<><button onClick={()=>setMobileSection(mobileSection===to?null:to)} aria-expanded={mobileSection===to}>{label}<ChevronDown/></button><AnimatePresence>{mobileSection===to&&<motion.section initial={{height:0}} animate={{height:'auto'}} exit={{height:0}}>{catalogues[to].items.map(x=><Link to={x.to} key={x.name}>{x.name}<small>{x.meta}</small></Link>)}<Link to={to}>View all</Link></motion.section>}</AnimatePresence></>:<NavLink to={to}>{label}</NavLink>}</motion.div>)}</nav><footer><a href={contact.tel}><Phone/>Call</a><a href={contact.whatsapp}><MessageCircle/>WhatsApp</a></footer></motion.div></motion.div>}</AnimatePresence></>
}
