import { FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import { ChevronDown, Mail, MessageCircle, Phone, Send } from 'lucide-react'
import { articles, contact, destinations } from '../data/content'
import { PageHero, Reveal, SectionHead } from '../components/ui/Primitives'

export function GuidePage(){
  const topics=[['Temple Etiquette','Respectful clothing, footwear, photography and offering guidance.'],['Packing Checklist','Documents, medicines and layers for changing climates.'],['Best Season','Weather and route considerations across sacred India.'],['Darshan Information','Planning around temple timings, queues and local rules.'],['Festival Calendar','Understanding important celebrations and seasonal demand.'],['Health & Comfort','Pacing, hydration and mobility preparation for every age.']]
  return <><PageHero eyebrow="The pilgrimage library" title="Travel prepared. Arrive with peace." copy="Practical guidance for temple visits, sacred routes and comfortable devotional travel." image="/images/char-dham.png"/><section className="page-section container"><SectionHead eyebrow="Knowledge for the journey" title="Clear guidance, thoughtfully organized."/><div className="topic-list">{topics.map(([name,copy],i)=><Reveal key={name}><span>0{i+1}</span><h3>{name}</h3><p>{copy}</p></Reveal>)}</div><section className="guide-feature"><img loading="lazy" src="/images/tirupati.png" alt="Tirupati temple"/><div><p>Featured guide</p><h2>Tirupati Balaji Darshan Guide</h2><span>Preparation, temple customs, local places and practical information for a meaningful visit.</span><Link to="/contact">Ask a pilgrimage expert</Link></div></section></section></>
}
export function BlogPage(){const [query,setQuery]=useState('');const shown=articles.filter(a=>a.title.toLowerCase().includes(query.toLowerCase()));return <><PageHero eyebrow="The Kakani journal" title="Stories, traditions and travel wisdom." copy="Read temple histories, practical pilgrimage guides and reflections from sacred India." image="/images/golden-temple-hero.png"/><section className="page-section container"><label className="article-search"><span>Search the journal</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Temple, destination or guide"/></label><div className="article-layout">{shown.map((a,i)=><Reveal className={i===0?'article-feature':''} key={a.slug}><article><img loading="lazy" src={a.image} alt={a.title}/><div><span>{a.category} · {a.readTime}</span><h2>{a.title}</h2><p>{a.excerpt}</p><Link to="/contact">Read story</Link></div></article></Reveal>)}</div></section></>}
export function AboutPage(){return <><PageHero eyebrow="Our story" title="Care is the journey behind the journey." copy="Kakani Holidays brings route knowledge and human guidance together for meaningful spiritual travel." image="/images/hindu-temple-hero.png"/><section className="about-new container"><Reveal><SectionHead eyebrow="The Kakani Way" title="Responsibility in every detail."/><p>From sacred rivers to ancient temples, every route is shaped around comfort, clarity and the purpose of the journey. Our role is to make the practical details feel considered so travellers can remain present for what matters.</p></Reveal><Reveal><img loading="lazy" src="/images/char-dham.png" alt="Himalayan temple pilgrimage"/></Reveal></section><section className="principles container"><SectionHead eyebrow="What guides us" title="Trust, devotion and personal care."/><div>{['Expert destination guidance','Comfortable stays near sacred places','Well-planned routes and operations','Personalized service for every devotee'].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3></article>)}</div></section></>}
export function ContactPage(){const [status,setStatus]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();setStatus('This form needs a business email or CRM integration before it can send enquiries.')};return <><PageHero eyebrow="Pilgrimage concierge" title="Let us understand your journey." copy="Speak with our team about destinations, dates, traveller comfort and the right pace for your pilgrimage." image="/images/dwarka-somnath.png"/><section className="contact-new container"><div><SectionHead eyebrow="Direct assistance" title="A human voice when you need one."/><a href={contact.tel}><Phone/>{contact.phone}</a><a href={contact.whatsapp}><MessageCircle/>WhatsApp our team</a><a href={`mailto:${contact.email}`}><Mail/>{contact.email}</a></div><form onSubmit={submit}><div><label>Name<input required name="name"/></label><label>Phone<input required type="tel" name="phone"/></label></div><div><label>Destination<select name="destination"><option value="">Select destination</option>{destinations.map(d=><option key={d.slug}>{d.name}</option>)}</select></label><label>Travel date<input type="date" name="date"/></label></div><label>Message<textarea name="message" placeholder="Traveller count, departure city, mobility or darshan preferences"/></label><button>Request consultation <Send/></button><p role="status">{status}</p></form></section></>}
export function LegalPage({title}:{title:string}){return <main className="legal container"><h1>{title}</h1><p>This policy requires approved legal content from Kakani Holidays before publication.</p></main>}
